insert into public.dive_sites (name, region, country, latitude, longitude, short_description, full_description, max_depth_m, avg_depth_m, visibility_range_m, water_type, dive_type, skill_level, tags, image_url, rating) values
('Great Blue Hole', 'Caribbean', 'Belize', 17.316, -87.535, 'Amazing wall dive at Great Blue Hole.', 'Detailed log for Great Blue Hole', 40, 28, 24, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, 'https://images.unsplash.com/photo-1544551763-46a0e38eeba6?q=80&w=800&auto=format&fit=crop', 4.9),
('Molasses Reef', 'Florida Keys', 'USA', 25.008, -80.375, 'Amazing reef dive at Molasses Reef.', 'Detailed log for Molasses Reef', 12, 8, 20, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, 'https://images.unsplash.com/photo-1582967788606-a171c1080cb0?q=80&w=800&auto=format&fit=crop', 4.8),
('Cenote Dos Ojos', 'Yucatan', 'Mexico', 20.324, -87.391, 'Amazing cave dive at Cenote Dos Ojos.', 'Detailed log for Cenote Dos Ojos', 10, 7, 30, 'Saltwater', 'Cave', 'Intermediate', '[]'::jsonb, '', 0.0),
('Kailua Kona Manta Ray Night Dive', 'Hawaii', 'USA', 19.64, -156, 'Amazing night dive at Kailua Kona Manta Ray Night Dive.', 'Detailed log for Kailua Kona Manta Ray Night Dive', 15, 10, 32, 'Saltwater', 'Night', 'Intermediate', '[]'::jsonb, '', 0.0),
('Bloody Bay Wall', 'Caribbean', 'Cayman Islands', 19.684, -80.052, 'Amazing wall dive at Bloody Bay Wall.', 'Detailed log for Bloody Bay Wall', 30, 21, 22, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Palancar Reef', 'Caribbean', 'Mexico', 20.34, -87.03, 'Amazing drift dive at Palancar Reef.', 'Detailed log for Palancar Reef', 25, 17, 30, 'Saltwater', 'Drift', 'Intermediate', '[]'::jsonb, '', 0.0),
('Marys Place', 'Caribbean', 'Honduras', 16.32, -86.53, 'Amazing reef dive at Marys Place.', 'Detailed log for Marys Place', 30, 21, 32, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('Tiger Beach', 'Grand Bahama', 'Bahamas', 26.83, -79.16, 'Amazing shark dive at Tiger Beach.', 'Detailed log for Tiger Beach', 8, 5, 25, 'Saltwater', 'Shark', 'Intermediate', '[]'::jsonb, '', 0.0),
('Stingray City', 'Grand Cayman', 'Cayman Islands', 19.37, -81.33, 'Amazing animal interaction dive at Stingray City.', 'Detailed log for Stingray City', 4, 2, 30, 'Saltwater', 'Animal Interaction', 'Intermediate', '[]'::jsonb, '', 0.0),
('Christ of the Abyss', 'Florida Keys', 'USA', 25.12, -80.2, 'Amazing reef dive at Christ of the Abyss.', 'Detailed log for Christ of the Abyss', 8, 5, 27, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('USS Spiegel Grove', 'Florida Keys', 'USA', 25.06, -80.3, 'Amazing wreck dive at USS Spiegel Grove.', 'Detailed log for USS Spiegel Grove', 39, 27, 17, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('USNS General Hoyt S. Vandenberg', 'Florida Keys', 'USA', 24.45, -81.76, 'Amazing wreck dive at USNS General Hoyt S. Vandenberg.', 'Detailed log for USNS General Hoyt S. Vandenberg', 42, 29, 34, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Shark Ray Alley', 'Ambergris Caye', 'Belize', 17.88, -87.98, 'Amazing reef dive at Shark Ray Alley.', 'Detailed log for Shark Ray Alley', 5, 3, 27, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Silverside Caves', 'Grand Cayman', 'Cayman Islands', 19.28, -81.39, 'Amazing cave dive at Silverside Caves.', 'Detailed log for Silverside Caves', 15, 10, 18, 'Saltwater', 'Cave', 'Intermediate', '[]'::jsonb, '', 0.0),
('Half Moon Caye Wall', 'Lighthouse Reef', 'Belize', 17.2, -87.53, 'Amazing wall dive at Half Moon Caye Wall.', 'Detailed log for Half Moon Caye Wall', 30, 21, 18, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('C-53 Wreck', 'Cozumel', 'Mexico', 20.46, -86.95, 'Amazing wreck dive at C-53 Wreck.', 'Detailed log for C-53 Wreck', 25, 17, 27, 'Saltwater', 'Wreck', 'Intermediate', '[]'::jsonb, '', 0.0),
('The Elbow', 'Turneffe Atoll', 'Belize', 17.25, -87.82, 'Amazing wall dive at The Elbow.', 'Detailed log for The Elbow', 35, 24, 18, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Bakers Half Dozen', 'Bimini', 'Bahamas', 25.73, -79.31, 'Amazing reef dive at Bakers Half Dozen.', 'Detailed log for Bakers Half Dozen', 15, 10, 34, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Over the Wall', 'Andros', 'Bahamas', 24.81, -77.85, 'Amazing wall dive at Over the Wall.', 'Detailed log for Over the Wall', 40, 28, 22, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Santa Rosa Wall', 'Cozumel', 'Mexico', 20.37, -87.01, 'Amazing wall dive at Santa Rosa Wall.', 'Detailed log for Santa Rosa Wall', 30, 21, 25, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Columbia Deep', 'Cozumel', 'Mexico', 20.31, -87.02, 'Amazing drift dive at Columbia Deep.', 'Detailed log for Columbia Deep', 28, 19, 25, 'Saltwater', 'Drift', 'Advanced', '[]'::jsonb, '', 0.0),
('Hole in the Wall', 'Roatan', 'Honduras', 16.32, -86.58, 'Amazing cave dive at Hole in the Wall.', 'Detailed log for Hole in the Wall', 35, 24, 26, 'Saltwater', 'Cave', 'Advanced', '[]'::jsonb, '', 0.0),
('Cara a Cara', 'Roatan', 'Honduras', 16.29, -86.55, 'Amazing shark dive at Cara a Cara.', 'Detailed log for Cara a Cara', 22, 15, 28, 'Saltwater', 'Shark', 'Intermediate', '[]'::jsonb, '', 0.0),
('Mushroom Forest', 'Curacao', 'Curacao', 12.28, -69.15, 'Amazing reef dive at Mushroom Forest.', 'Detailed log for Mushroom Forest', 18, 12, 20, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Superior Producer', 'Curacao', 'Curacao', 12.11, -68.94, 'Amazing wreck dive at Superior Producer.', 'Detailed log for Superior Producer', 30, 21, 28, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Hilma Hooker', 'Bonaire', 'Bonaire', 12.1, -68.28, 'Amazing wreck dive at Hilma Hooker.', 'Detailed log for Hilma Hooker', 30, 21, 25, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Salt Pier', 'Bonaire', 'Bonaire', 12.08, -68.28, 'Amazing night dive at Salt Pier.', 'Detailed log for Salt Pier', 15, 10, 26, 'Saltwater', 'Night', 'Intermediate', '[]'::jsonb, '', 0.0),
('Carmel Pinnacles', 'California', 'USA', 36.56, -121.96, 'Amazing kelp forest dive at Carmel Pinnacles.', 'Detailed log for Carmel Pinnacles', 30, 21, 18, 'Saltwater', 'Kelp Forest', 'Advanced', '[]'::jsonb, '', 0.0),
('Casino Point', 'Catalina Island', 'USA', 33.35, -118.32, 'Amazing kelp forest dive at Casino Point.', 'Detailed log for Casino Point', 20, 14, 31, 'Saltwater', 'Kelp Forest', 'Intermediate', '[]'::jsonb, '', 0.0),
('San Clemente Island', 'California', 'USA', 32.9, -118.49, 'Amazing kelp forest dive at San Clemente Island.', 'Detailed log for San Clemente Island', 25, 17, 31, 'Saltwater', 'Kelp Forest', 'Intermediate', '[]'::jsonb, '', 0.0),
('Gordon Rocks', 'Galapagos', 'Ecuador', -0.495, -90.045, 'Amazing reef dive at Gordon Rocks.', 'Detailed log for Gordon Rocks', 30, 21, 27, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('Darwins Arch', 'Galapagos', 'Ecuador', 1.67, -92, 'Amazing shark dive at Darwins Arch.', 'Detailed log for Darwins Arch', 35, 24, 28, 'Saltwater', 'Shark', 'Advanced', '[]'::jsonb, '', 0.0),
('Wolf Island', 'Galapagos', 'Ecuador', 1.38, -91.81, 'Amazing shark dive at Wolf Island.', 'Detailed log for Wolf Island', 30, 21, 29, 'Saltwater', 'Shark', 'Advanced', '[]'::jsonb, '', 0.0),
('Kicker Rock', 'Galapagos', 'Ecuador', -0.76, -89.44, 'Amazing wall dive at Kicker Rock.', 'Detailed log for Kicker Rock', 40, 28, 21, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Fernando de Noronha', 'Atlantic', 'Brazil', -3.85, -32.42, 'Amazing reef dive at Fernando de Noronha.', 'Detailed log for Fernando de Noronha', 25, 17, 27, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Laje de Santos', 'Sao Paulo', 'Brazil', -24.32, -46.18, 'Amazing manta dive at Laje de Santos.', 'Detailed log for Laje de Santos', 25, 17, 16, 'Saltwater', 'Manta', 'Intermediate', '[]'::jsonb, '', 0.0),
('Malpelo Island', 'Pacific', 'Colombia', 4, -81.6, 'Amazing shark dive at Malpelo Island.', 'Detailed log for Malpelo Island', 40, 28, 15, 'Saltwater', 'Shark', 'Advanced', '[]'::jsonb, '', 0.0),
('Bajo Alcyone', 'Cocos Island', 'Costa Rica', 5.53, -87.05, 'Amazing shark dive at Bajo Alcyone.', 'Detailed log for Bajo Alcyone', 35, 24, 29, 'Saltwater', 'Shark', 'Advanced', '[]'::jsonb, '', 0.0),
('Manuelita', 'Cocos Island', 'Costa Rica', 5.55, -87.04, 'Amazing night dive at Manuelita.', 'Detailed log for Manuelita', 30, 21, 33, 'Saltwater', 'Night', 'Advanced', '[]'::jsonb, '', 0.0),
('Dirty Rock', 'Cocos Island', 'Costa Rica', 5.54, -87.06, 'Amazing reef dive at Dirty Rock.', 'Detailed log for Dirty Rock', 35, 24, 31, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('Silfra Fissure', 'Thingvellir', 'Iceland', 64.256, -21.117, 'Amazing freshwater dive at Silfra Fissure.', 'Detailed log for Silfra Fissure', 18, 12, 15, 'Saltwater', 'Freshwater', 'Intermediate', '[]'::jsonb, '', 0.0),
('MS Zenobia', 'Mediterranean', 'Cyprus', 34.887, 33.65, 'Amazing wreck dive at MS Zenobia.', 'Detailed log for MS Zenobia', 42, 29, 34, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Scapa Flow', 'Orkney', 'UK', 58.89, -3.07, 'Amazing wreck dive at Scapa Flow.', 'Detailed log for Scapa Flow', 40, 28, 33, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Blockship Tabarka', 'Orkney', 'UK', 58.88, -3.06, 'Amazing wreck dive at Blockship Tabarka.', 'Detailed log for Blockship Tabarka', 15, 10, 29, 'Saltwater', 'Wreck', 'Intermediate', '[]'::jsonb, '', 0.0),
('Medes Islands', 'Catalonia', 'Spain', 42.05, 3.22, 'Amazing reef dive at Medes Islands.', 'Detailed log for Medes Islands', 25, 17, 17, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Blue Hole', 'Gozo', 'Malta', 36.05, 14.19, 'Amazing cave dive at Blue Hole.', 'Detailed log for Blue Hole', 30, 21, 21, 'Saltwater', 'Cave', 'Advanced', '[]'::jsonb, '', 0.0),
('Um El Faroud', 'Valletta', 'Malta', 35.82, 14.45, 'Amazing wreck dive at Um El Faroud.', 'Detailed log for Um El Faroud', 35, 24, 19, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Rozi Tugboat', 'Cirkewwa', 'Malta', 35.98, 14.33, 'Amazing wreck dive at Rozi Tugboat.', 'Detailed log for Rozi Tugboat', 35, 24, 21, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Il-Pofin', 'Gozo', 'Malta', 36.04, 14.2, 'Amazing wall dive at Il-Pofin.', 'Detailed log for Il-Pofin', 40, 28, 17, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Le Donator', 'Port-Cros', 'France', 43, 6.25, 'Amazing wreck dive at Le Donator.', 'Detailed log for Le Donator', 48, 33, 34, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Le Rubis', 'St Tropez', 'France', 43.2, 6.66, 'Amazing wreck dive at Le Rubis.', 'Detailed log for Le Rubis', 40, 28, 15, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Chios Cave', 'Aegean', 'Greece', 38.37, 26.13, 'Amazing cave dive at Chios Cave.', 'Detailed log for Chios Cave', 20, 14, 16, 'Saltwater', 'Cave', 'Intermediate', '[]'::jsonb, '', 0.0),
('Baron Gautsch', 'Istria', 'Croatia', 44.95, 13.6, 'Amazing wreck dive at Baron Gautsch.', 'Detailed log for Baron Gautsch', 40, 28, 18, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Chinhou Wreck', 'Pula', 'Croatia', 44.75, 13.8, 'Amazing wreck dive at Chinhou Wreck.', 'Detailed log for Chinhou Wreck', 45, 31, 15, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Lofoten Kelp Forests', 'Lofoten', 'Norway', 68.2, 13.5, 'Amazing cold water dive at Lofoten Kelp Forests.', 'Detailed log for Lofoten Kelp Forests', 15, 10, 18, 'Saltwater', 'Cold Water', 'Intermediate', '[]'::jsonb, '', 0.0),
('SS Thistlegorm', 'Red Sea', 'Egypt', 27.814, 33.918, 'Amazing wreck dive at SS Thistlegorm.', 'Detailed log for SS Thistlegorm', 30, 21, 29, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?q=80&w=800&auto=format&fit=crop', 4.9),
('Ras Mohammed', 'Red Sea', 'Egypt', 27.72, 34.25, 'Amazing wall dive at Ras Mohammed.', 'Detailed log for Ras Mohammed', 25, 17, 23, 'Saltwater', 'Wall', 'Intermediate', '[]'::jsonb, '', 0.0),
('Aliwal Shoal', 'KwaZulu-Natal', 'South Africa', -30.26, 30.82, 'Amazing reef dive at Aliwal Shoal.', 'Detailed log for Aliwal Shoal', 25, 17, 28, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Sardine Run', 'Wild Coast', 'South Africa', -31.6, 29.5, 'Amazing drift dive at Sardine Run.', 'Detailed log for Sardine Run', 20, 14, 27, 'Saltwater', 'Drift', 'Intermediate', '[]'::jsonb, '', 0.0),
('Brothers Islands', 'Red Sea', 'Egypt', 26.31, 34.84, 'Amazing wall dive at Brothers Islands.', 'Detailed log for Brothers Islands', 40, 28, 21, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Daedalus Reef', 'Red Sea', 'Egypt', 24.93, 35.88, 'Amazing shark dive at Daedalus Reef.', 'Detailed log for Daedalus Reef', 40, 28, 29, 'Saltwater', 'Shark', 'Advanced', '[]'::jsonb, '', 0.0),
('Elphinstone Reef', 'Red Sea', 'Egypt', 25.31, 34.87, 'Amazing shark dive at Elphinstone Reef.', 'Detailed log for Elphinstone Reef', 40, 28, 23, 'Saltwater', 'Shark', 'Advanced', '[]'::jsonb, '', 0.0),
('Jackson Reef', 'Tiran', 'Egypt', 28, 34.42, 'Amazing reef dive at Jackson Reef.', 'Detailed log for Jackson Reef', 30, 21, 21, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('Thomas Reef', 'Tiran', 'Egypt', 27.97, 34.4, 'Amazing wall dive at Thomas Reef.', 'Detailed log for Thomas Reef', 40, 28, 18, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Blue Hole Dahab', 'Dahab', 'Egypt', 28.57, 34.53, 'Amazing technical dive at Blue Hole Dahab.', 'Detailed log for Blue Hole Dahab', 110, 77, 17, 'Saltwater', 'Technical', 'Advanced', '[]'::jsonb, '', 0.0),
('The Canyon', 'Dahab', 'Egypt', 28.55, 34.52, 'Amazing cave dive at The Canyon.', 'Detailed log for The Canyon', 30, 21, 29, 'Saltwater', 'Cave', 'Advanced', '[]'::jsonb, '', 0.0),
('Salem Express', 'Safaga', 'Egypt', 26.63, 34.12, 'Amazing wreck dive at Salem Express.', 'Detailed log for Salem Express', 32, 22, 17, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Protea Banks', 'KwaZulu-Natal', 'South Africa', -30.82, 30.47, 'Amazing shark dive at Protea Banks.', 'Detailed log for Protea Banks', 35, 24, 24, 'Saltwater', 'Shark', 'Advanced', '[]'::jsonb, '', 0.0),
('Cape Point', 'Cape Town', 'South Africa', -34.35, 18.48, 'Amazing kelp dive at Cape Point.', 'Detailed log for Cape Point', 20, 14, 20, 'Saltwater', 'Kelp', 'Intermediate', '[]'::jsonb, '', 0.0),
('2 Mile Reef', 'Sodwana Bay', 'South Africa', -27.53, 32.68, 'Amazing reef dive at 2 Mile Reef.', 'Detailed log for 2 Mile Reef', 18, 12, 27, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Manta Reef', 'Tofo', 'Mozambique', -23.85, 35.55, 'Amazing manta dive at Manta Reef.', 'Detailed log for Manta Reef', 25, 17, 19, 'Saltwater', 'Manta', 'Intermediate', '[]'::jsonb, '', 0.0),
('Quirimbas Archipelago', 'Pemba', 'Mozambique', -12.45, 40.6, 'Amazing reef dive at Quirimbas Archipelago.', 'Detailed log for Quirimbas Archipelago', 20, 14, 26, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Two Mile Reef', 'Bazaruto', 'Mozambique', -21.8, 35.5, 'Amazing reef dive at Two Mile Reef.', 'Detailed log for Two Mile Reef', 20, 14, 17, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Nosy Be', 'Madagascar', 'Madagascar', -13.33, 48.24, 'Amazing reef dive at Nosy Be.', 'Detailed log for Nosy Be', 25, 17, 18, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Mumbo Island', 'Lake Malawi', 'Malawi', -13.98, 34.75, 'Amazing freshwater dive at Mumbo Island.', 'Detailed log for Mumbo Island', 15, 10, 23, 'Saltwater', 'Freshwater', 'Intermediate', '[]'::jsonb, '', 0.0),
('Richelieu Rock', 'Andaman Sea', 'Thailand', 9.362, 98.022, 'Amazing reef dive at Richelieu Rock.', 'Detailed log for Richelieu Rock', 35, 24, 29, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('Barracuda Point', 'Sipadan', 'Malaysia', 4.114, 118.628, 'Amazing wall dive at Barracuda Point.', 'Detailed log for Barracuda Point', 40, 28, 33, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Cape Kri', 'Raja Ampat', 'Indonesia', -0.558, 130.654, 'Amazing reef dive at Cape Kri.', 'Detailed log for Cape Kri', 40, 28, 24, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('USAT Liberty', 'Bali', 'Indonesia', -8.274, 115.591, 'Amazing wreck dive at USAT Liberty.', 'Detailed log for USAT Liberty', 30, 21, 27, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Manta Alley', 'Komodo', 'Indonesia', -8.76, 119.58, 'Amazing drift dive at Manta Alley.', 'Detailed log for Manta Alley', 25, 17, 28, 'Saltwater', 'Drift', 'Intermediate', '[]'::jsonb, '', 0.0),
('Elephant Head Rock', 'Similan Islands', 'Thailand', 8.6, 97.6, 'Amazing reef dive at Elephant Head Rock.', 'Detailed log for Elephant Head Rock', 30, 21, 19, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('Tubbataha Reefs', 'Sulu Sea', 'Philippines', 8.8, 119.9, 'Amazing wall dive at Tubbataha Reefs.', 'Detailed log for Tubbataha Reefs', 30, 21, 19, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Monad Shoal', 'Malapascua', 'Philippines', 11.3, 124.15, 'Amazing shark dive at Monad Shoal.', 'Detailed log for Monad Shoal', 30, 21, 22, 'Saltwater', 'Shark', 'Advanced', '[]'::jsonb, '', 0.0),
('Apo Reef', 'Mindoro', 'Philippines', 12.66, 120.48, 'Amazing wall dive at Apo Reef.', 'Detailed log for Apo Reef', 40, 28, 26, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Irako Wreck', 'Coron', 'Philippines', 11.96, 120.02, 'Amazing wreck dive at Irako Wreck.', 'Detailed log for Irako Wreck', 42, 29, 18, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Dauin Muck', 'Negros', 'Philippines', 9.19, 123.27, 'Amazing muck dive at Dauin Muck.', 'Detailed log for Dauin Muck', 15, 10, 28, 'Saltwater', 'Muck', 'Intermediate', '[]'::jsonb, '', 0.0),
('Batu Bolong', 'Komodo', 'Indonesia', -8.53, 119.51, 'Amazing reef dive at Batu Bolong.', 'Detailed log for Batu Bolong', 30, 21, 32, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('Crystal Bay', 'Nusa Penida', 'Indonesia', -8.71, 115.45, 'Amazing open ocean dive at Crystal Bay.', 'Detailed log for Crystal Bay', 40, 28, 24, 'Saltwater', 'Open Ocean', 'Advanced', '[]'::jsonb, '', 0.0),
('Manta Point', 'Nusa Penida', 'Indonesia', -8.8, 115.53, 'Amazing manta dive at Manta Point.', 'Detailed log for Manta Point', 12, 8, 27, 'Saltwater', 'Manta', 'Intermediate', '[]'::jsonb, '', 0.0),
('Hairball', 'Lembeh Strait', 'Indonesia', 1.45, 125.21, 'Amazing muck dive at Hairball.', 'Detailed log for Hairball', 15, 10, 29, 'Saltwater', 'Muck', 'Intermediate', '[]'::jsonb, '', 0.0),
('Lekuan I', 'Bunaken', 'Indonesia', 1.62, 124.76, 'Amazing wall dive at Lekuan I.', 'Detailed log for Lekuan I', 40, 28, 29, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Roma', 'Wakatobi', 'Indonesia', -5.73, 123.95, 'Amazing reef dive at Roma.', 'Detailed log for Roma', 25, 17, 28, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('The Drop Off', 'Sipadan', 'Malaysia', 4.11, 118.63, 'Amazing wall dive at The Drop Off.', 'Detailed log for The Drop Off', 40, 28, 34, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Gorgonian Forest', 'Layang-Layang', 'Malaysia', 7.37, 113.84, 'Amazing wall dive at Gorgonian Forest.', 'Detailed log for Gorgonian Forest', 40, 28, 31, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Chumphon Pinnacle', 'Koh Tao', 'Thailand', 10.18, 99.81, 'Amazing reef dive at Chumphon Pinnacle.', 'Detailed log for Chumphon Pinnacle', 35, 24, 31, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('SS Yongala', 'Queensland', 'Australia', -19.309, 147.616, 'Amazing wreck dive at SS Yongala.', 'Detailed log for SS Yongala', 28, 19, 15, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Blue Corner', 'Rock Islands', 'Palau', 7.13, 134.22, 'Amazing drift dive at Blue Corner.', 'Detailed log for Blue Corner', 30, 21, 16, 'Saltwater', 'Drift', 'Advanced', '[]'::jsonb, '', 0.0),
('Cod Hole', 'Great Barrier Reef', 'Australia', -14.66, 145.62, 'Amazing reef dive at Cod Hole.', 'Detailed log for Cod Hole', 15, 10, 28, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Rainbow Reef', 'Taveuni', 'Fiji', -16.78, 179.98, 'Amazing reef dive at Rainbow Reef.', 'Detailed log for Rainbow Reef', 25, 17, 27, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('SS President Coolidge', 'Espiritu Santo', 'Vanuatu', -15.52, 167.24, 'Amazing wreck dive at SS President Coolidge.', 'Detailed log for SS President Coolidge', 60, 42, 15, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('North Horn', 'Coral Sea', 'Australia', -13.9, 146.6, 'Amazing shark dive at North Horn.', 'Detailed log for North Horn', 40, 28, 19, 'Saltwater', 'Shark', 'Advanced', '[]'::jsonb, '', 0.0),
('Steve Bommie', 'Great Barrier Reef', 'Australia', -15.48, 145.8, 'Amazing reef dive at Steve Bommie.', 'Detailed log for Steve Bommie', 30, 21, 32, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('Navy Pier', 'Exmouth', 'Australia', -21.82, 114.16, 'Amazing reef dive at Navy Pier.', 'Detailed log for Navy Pier', 15, 10, 30, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Ningaloo Reef', 'Western Australia', 'Australia', -22.5, 113.8, 'Amazing whale shark dive at Ningaloo Reef.', 'Detailed log for Ningaloo Reef', 15, 10, 25, 'Saltwater', 'Whale Shark', 'Intermediate', '[]'::jsonb, '', 0.0),
('Peleliu Express', 'Peleliu', 'Palau', 6.96, 134.22, 'Amazing drift dive at Peleliu Express.', 'Detailed log for Peleliu Express', 40, 28, 34, 'Saltwater', 'Drift', 'Advanced', '[]'::jsonb, '', 0.0),
('Ulithi Atoll', 'Caroline Islands', 'Micronesia', 9.95, 139.6, 'Amazing wall dive at Ulithi Atoll.', 'Detailed log for Ulithi Atoll', 30, 21, 17, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Fujikawa Maru', 'Chuuk', 'Micronesia', 7.37, 151.86, 'Amazing wreck dive at Fujikawa Maru.', 'Detailed log for Fujikawa Maru', 34, 23, 21, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Milne Bay Muck', 'Papua New Guinea', 'Papua New Guinea', -10.31, 150.36, 'Amazing muck dive at Milne Bay Muck.', 'Detailed log for Milne Bay Muck', 15, 10, 29, 'Saltwater', 'Muck', 'Intermediate', '[]'::jsonb, '', 0.0),
('South Emma', 'New Britain', 'Papua New Guinea', -5.5, 150.1, 'Amazing reef dive at South Emma.', 'Detailed log for South Emma', 30, 21, 27, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('Albatross Passage', 'New Ireland', 'Papua New Guinea', -2.65, 150.7, 'Amazing drift dive at Albatross Passage.', 'Detailed log for Albatross Passage', 35, 24, 24, 'Saltwater', 'Drift', 'Advanced', '[]'::jsonb, '', 0.0),
('Witu Islands', 'Bismarck Sea', 'Papua New Guinea', -4.68, 149.44, 'Amazing reef dive at Witu Islands.', 'Detailed log for Witu Islands', 25, 17, 27, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('South Pass', 'Fakarava Atoll', 'French Polynesia', -16.51, -145.46, 'Amazing shark dive at South Pass.', 'Detailed log for South Pass', 30, 21, 29, 'Saltwater', 'Shark', 'Advanced', '[]'::jsonb, '', 0.0),
('Tiputa Pass', 'Rangiroa', 'French Polynesia', -14.96, -147.61, 'Amazing drift dive at Tiputa Pass.', 'Detailed log for Tiputa Pass', 35, 24, 19, 'Saltwater', 'Drift', 'Advanced', '[]'::jsonb, '', 0.0),
('Boreas Wreck', 'Catalonia', 'Spain', 41.8, 3.06, 'Amazing wreck dive at Boreas Wreck.', 'Detailed log for Boreas Wreck', 30, 21, 18, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Umbria Wreck', 'Red Sea', 'Sudan', 19.63, 37.31, 'Amazing wreck dive at Umbria Wreck.', 'Detailed log for Umbria Wreck', 38, 26, 26, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Sanganeb', 'Red Sea', 'Sudan', 19.74, 37.43, 'Amazing wall dive at Sanganeb.', 'Detailed log for Sanganeb', 40, 28, 15, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Seven Brothers', 'Bab el Mandeb', 'Djibouti', 12.46, 43.41, 'Amazing drift dive at Seven Brothers.', 'Detailed log for Seven Brothers', 30, 21, 15, 'Saltwater', 'Drift', 'Advanced', '[]'::jsonb, '', 0.0),
('Hanifaru Bay', 'Baa Atoll', 'Maldives', 5.17, 73.11, 'Amazing manta dive at Hanifaru Bay.', 'Detailed log for Hanifaru Bay', 10, 7, 32, 'Saltwater', 'Manta', 'Intermediate', '[]'::jsonb, '', 0.0),
('Maya Thila', 'Ari Atoll', 'Maldives', 4.02, 72.84, 'Amazing night dive at Maya Thila.', 'Detailed log for Maya Thila', 30, 21, 26, 'Saltwater', 'Night', 'Advanced', '[]'::jsonb, '', 0.0),
('Alimatha Jetty', 'Vaavu Atoll', 'Maldives', 3.6, 73.54, 'Amazing night dive at Alimatha Jetty.', 'Detailed log for Alimatha Jetty', 15, 10, 30, 'Saltwater', 'Night', 'Intermediate', '[]'::jsonb, '', 0.0),
('Fotteyo Kandu', 'Vaavu Atoll', 'Maldives', 3.42, 73.74, 'Amazing wall dive at Fotteyo Kandu.', 'Detailed log for Fotteyo Kandu', 40, 28, 34, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('HMS Hermes', 'Trincomalee', 'Sri Lanka', 8.53, 81.25, 'Amazing technical dive at HMS Hermes.', 'Detailed log for HMS Hermes', 53, 37, 28, 'Saltwater', 'Technical', 'Advanced', '[]'::jsonb, '', 0.0),
('Dixons Pinnacle', 'Havelock', 'India', 11.96, 93, 'Amazing reef dive at Dixons Pinnacle.', 'Detailed log for Dixons Pinnacle', 35, 24, 18, 'Saltwater', 'Reef', 'Advanced', '[]'::jsonb, '', 0.0),
('Princess Royal Wreck', 'Bangaram', 'India', 10.95, 72.23, 'Amazing wreck dive at Princess Royal Wreck.', 'Detailed log for Princess Royal Wreck', 32, 22, 24, 'Saltwater', 'Wreck', 'Advanced', '[]'::jsonb, '', 0.0),
('Turtle Island', 'Phu Quoc', 'Vietnam', 10.36, 103.88, 'Amazing reef dive at Turtle Island.', 'Detailed log for Turtle Island', 12, 8, 22, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Green Island', 'Pacific', 'Taiwan', 22.66, 121.48, 'Amazing reef dive at Green Island.', 'Detailed log for Green Island', 25, 17, 26, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Yonaguni Monument', 'Ryukyu Islands', 'Japan', 24.43, 123, 'Amazing ruins dive at Yonaguni Monument.', 'Detailed log for Yonaguni Monument', 25, 17, 26, 'Saltwater', 'Ruins', 'Intermediate', '[]'::jsonb, '', 0.0),
('Throne Room', 'Negril', 'Jamaica', 18.27, -78.36, 'Amazing cave dive at Throne Room.', 'Detailed log for Throne Room', 20, 14, 22, 'Saltwater', 'Cave', 'Intermediate', '[]'::jsonb, '', 0.0),
('Widowmakers Cave', 'Montego Bay', 'Jamaica', 18.49, -77.93, 'Amazing cave dive at Widowmakers Cave.', 'Detailed log for Widowmakers Cave', 25, 17, 21, 'Saltwater', 'Cave', 'Intermediate', '[]'::jsonb, '', 0.0),
('SS Kathryn Wreck', 'Ocho Rios', 'Jamaica', 18.41, -77.1, 'Amazing wreck dive at SS Kathryn Wreck.', 'Detailed log for SS Kathryn Wreck', 15, 10, 27, 'Saltwater', 'Wreck', 'Intermediate', '[]'::jsonb, '', 0.0),
('Texas', 'Montego Bay', 'Jamaica', 18.5, -77.94, 'Amazing wall dive at Texas.', 'Detailed log for Texas', 35, 24, 24, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('Devils Reef', 'Ocho Rios', 'Jamaica', 18.42, -77.11, 'Amazing wall dive at Devils Reef.', 'Detailed log for Devils Reef', 40, 28, 25, 'Saltwater', 'Wall', 'Advanced', '[]'::jsonb, '', 0.0),
('The Arches', 'Montego Bay', 'Jamaica', 18.48, -77.92, 'Amazing reef dive at The Arches.', 'Detailed log for The Arches', 12, 8, 31, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('The Point', 'Negril', 'Jamaica', 18.32, -78.34, 'Amazing reef dive at The Point.', 'Detailed log for The Point', 25, 17, 22, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('English Reef', 'Negril', 'Jamaica', 18.25, -78.35, 'Amazing reef dive at English Reef.', 'Detailed log for English Reef', 20, 14, 20, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Sharks Reef', 'Negril', 'Jamaica', 18.28, -78.37, 'Amazing reef dive at Sharks Reef.', 'Detailed log for Sharks Reef', 18, 12, 32, 'Saltwater', 'Reef', 'Intermediate', '[]'::jsonb, '', 0.0),
('Sunken City of Port Royal', 'Kingston', 'Jamaica', 17.93, -76.84, 'Amazing ruins dive at Sunken City of Port Royal.', 'Detailed log for Sunken City of Port Royal', 15, 10, 33, 'Saltwater', 'Ruins', 'Intermediate', '[]'::jsonb, '', 0.0);

-- 2. Update Dive Sites with mission telemetry
update public.dive_sites 
set difficulty_score = floor(random() * 5 + 1),
    temp_range_min = floor(random() * 5 + 20),
    temp_range_max = floor(random() * 5 + 26);

-- 3. Populate Dive Shops
insert into public.dive_shops (name, location, website, rating) values
('Pro Dive International', 'Cozumel, Mexico', 'https://prodiveinternational.com', 4.8),
('Blue Magic Scuba', 'Cozumel, Mexico', 'https://bluemagicscuba.com', 4.9),
('Belize Dive Services', 'Caye Caulker, Belize', 'https://belizediveservices.com', 4.7),
('Deep Blue Divers', 'Grand Cayman', 'https://deepbluedivers.ky', 4.8),
('Sipadan Scuba', 'Mabul Island, Malaysia', 'https://sipadanscuba.com', 4.6),
('Oceanic Society', 'Belize City, Belize', 'https://oceanicsociety.org', 4.5);

-- 4. Populate Marine Life Catalog
insert into public.marine_life_species (name, scientific_name, category, rarity, image_url) values
('Whale Shark', 'Rhincodon typus', 'Sharks', 'Legendary', 'https://images.unsplash.com/photo-1560275619-4662e36fa65c'),
('Great White Shark', 'Carcharodon carcharias', 'Sharks', 'Rare', 'https://images.unsplash.com/photo-1564349683136-77e0891d0b06'),
('Manta Ray', 'Mobula alfredi', 'Rays', 'Legendary', 'https://images.unsplash.com/photo-1544551763-8dd44758c2dd'),
('Green Sea Turtle', 'Chelonia mydas', 'Turtles', 'Common', 'https://images.unsplash.com/photo-1544551763-47a0159291f2'),
('Lionfish', 'Pterois volitans', 'Fish', 'Common', 'https://images.unsplash.com/photo-1534043464124-3be32fe000c9'),
('Clownfish', 'Amphiprioninae', 'Fish', 'Common', 'https://images.unsplash.com/photo-1524704659698-1f6305c29631'),
('Spanish Dancer', 'Hexabranchus sanguineus', 'Nudibranchs', 'Uncommon', 'https://images.unsplash.com/photo-1516683018243-cd6d61f7f074');

-- 5. Create Test User Profile 
-- Note: auth.users must be created via Supabase Auth, but we can seed the public.profiles for a deterministic uuid
insert into public.profiles (id, display_name, username, certification_level, total_dives, home_country) values
('00000000-0000-0000-0000-000000000000', 'Reese Vierling', 'rcarvierling', 'Master Scuba Diver', 145, 'USA');

-- 6. Generate Hero Dive Logs
with logged_user as (select id from public.profiles where username = 'rcarvierling' limit 1),
     blue_hole as (select id from public.dive_sites where name = 'Great Blue Hole' limit 1),
     molasses as (select id from public.dive_sites where name = 'Molasses Reef' limit 1),
     abyss_shop as (select id from public.dive_shops where name = 'Abyss Pro Center' limit 1)
insert into public.dive_logs (user_id, dive_site_id, date, max_depth_m, bottom_time_min, water_temp_c, current_strength, rating, dive_shop_id) values
((select id from logged_user), (select id from blue_hole), '2026-04-01', 40.5, 35, 26, 'mild', 5, (select id from abyss_shop)),
((select id from logged_user), (select id from molasses), '2026-04-05', 18.2, 55, 28, 'none', 4, (select id from abyss_shop));

-- 7. Record Sighting Data
with logged_user as (select id from public.profiles where username = 'rcarvierling' limit 1),
     whale_shark as (select id from public.marine_life_species where name = 'Whale Shark' limit 1),
     blue_hole as (select id from public.dive_sites where name = 'Great Blue Hole' limit 1)
insert into public.user_marine_life_sightings (user_id, species_id, dive_site_id, date_seen) values
((select id from logged_user), (select id from whale_shark), (select id from blue_hole), '2026-04-01');